name: Build_Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, task0, task00, task1, task01, task2, task02, task3, task03, task5, task05, task6, task06, task7, task07, task8, task08, task9, task09]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install glfw
      run: |
        sudo apt-get update
        sudo apt-get install \
          xorg-dev libx11-dev \
          libglu1-mesa libglu1-mesa-dev \
          libgl1-mesa-glx libgl1-mesa-dev
        sudo apt-get install libglfw3
        sudo apt-get install libglfw3-dev

    - name: install eigen
      run: |
        sudo apt-get install libeigen3-dev

    - name: build
      run: |
        cmake .
        cmake --build .